project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Remote Sensing Cities and Environment"
  author: "Guk Yu"
  date: '`r Sys.Date()`'
  favicon: favicon-32x32.png
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - glossary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo, flatly]
        dark: [cosmo, darkly]
       
       
  pdf:
    documentclass: scrreprt

editor: visual



    