# Urban Heat Island

## Application
The impacts of the Urban Heat Island (UHI) effect have been difficult to ignore in recent years. Alongside rising global temperatures, higher temperatures experienced in urban areas pose a serious risk toward the health and wellbeing of urban populations. In the UK, the five-day heat wave in July 2022 was associated with 2,800 deaths in over-65s across the country as temperatures rose as high as 40C in central London. 

Physical factors contributing to UHI vulnerability are well documented. Key determinants of health risk include features of the built environment, such as buildings with high energy efficiency as well as the type of buildings themselves, with flats more susceptible to overheating than two-storey houses (Samuelson, et al 2020; Mavrogianni et al. 2009). Replacement of natural cover, such as trees and natural water features, with concrete roads and high-density buildings drastically reduces cities’ capacity to absorb heat, or increase albedo, further contributing to higher urban temperatures compared to surrounding non-urbanised areas (Mohajerani, 2017; Voskamp, 2015).

Neighbourhood socio-economic characteristics are also an important determinant of vulnerability. Harlan et al. (2013) conducted a comprehensive study identifying social and environmental predictors of heat vulnerability in Arizona. The study found deprived areas, especially those with majority black populations and areas of spatial deprivation (Nayak et al 2018; Madrigano et al 2015), where dwellings are considered overcrowded (Vellei et al. 2017), are particularly vulnerable to heat-related deaths. 

Often, it is exactly these poor urban areas that have the least access to green and blue covers and further away from hospitals for medical assistance (Prosdocimi and Klima 2020). Nicholl et al. (2007) found that risk of death is increased by 1.02% per kilometre of distance. 
